#!/bin/sh
set -e

cron_src="$(git rev-parse --show-toplevel)/pull-self.sh"
cron_dst='/etc/cron.hourly/pull-self.sh'

src_base="$(git rev-parse --show-toplevel)/kubernetes/alpha-cluster"
authkeys_src="$src_base/authorized_keys"
authkeys_dst='/root/.ssh/authorized_keys'
hosts_src="$src_base/hosts"
hosts_dst='/etc/hosts'

test $(id -u) -eq 0
test -e $authkeys_src
test -e $hosts_src

if ! [ "$(stat -c %a $authkeys_src)" = '600' ]; then
  chmod 0600 $authkeys_src
fi

if ! [ $(find $(dirname $authkeys_dst) -samefile $authkeys_src | wc -l) -gt 0 ]; then
  rm -f $authkeys_dst
  ln $authkeys_src $authkeys_dst
fi

if ! [ "$(readlink -f $hosts_dst)" = $hosts_src ]; then
  rm -f $hosts_dst
  ln -s $hosts_src $hosts_dst
fi

if ! [ "$(readlink -f $cron_src)" = $cron_dst]; then
  rm -f $cron_dst
  ln -s $cron_src $cron_dst
fi
