apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin
  namespace: yadaguru
spec:
  replicas: 1
  template:
    metadata:
      labels:
        id: admin
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: app
          image: yadaguru/admin:1.0.0
          ports:
            - containerPort: 80
