apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fluentd-aggregator-buffer
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4G
  volumeName: fluentd-aggregator.buffer
