---
- name: commit authority names
  when: domains[item]['authority'] is not defined
  shell: |
    import sys, sqlite3
    db = sqlite3.connect('{{ node_systemdb_path }}')
    db.executescript('''

      delete from {{ item }}_domain where attribute = "authority";

      insert into {{ item }}_domain (attribute, value)
      values ("authority", "{{ item }}.domain");

    ''')
    db.commit()
    db.close()
    sys.exit(0)
  args:
    executable: "{{ ansible_python.executable }}"
  loop:
    - system
    - node

- name: register authority names
  when: domains[item]['authority'] is not defined
  changed_when: new_supernet is defined
  register: node_supernet_set_job
  set_fact:
    domains: >-
      {{
          domains|
          combine({
            item: domains[item]|
            combine({ 'authority': item ~ '.domain' })
          })
      }}
  loop:
    - system
    - node
