---
- name: install git
  package: name=git-core state=present
- name: netdata repository
  git: repo=https://github.com/firehol/netdata.git dest=/root/netdata
- name: fetch netdata dependencies installer
  get_url:
    url: https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh
    dest: /root/netdata/netdata-install-required.sh
    mode: 0755
- name: install netdata
  shell: |
    set -e
    /root/netdata/netdata-install-required.sh --non-interactive -i netdata
    cd /root/netdata
    ./netdata-installer.sh --install /opt
  args:
    creates: /opt/netdata/etc/netdata/netdata.conf
