apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  namespace: yadaguru
spec:
  replicas: 1
  template:
    metadata:
      labels:
        id: app
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: app
          image: yadaguru/app:1.1.0
          ports:
            - containerPort: 80
