---
- name: node id
  when: authorities['node.domain']['id'] is not defined
  block:

    - name: create node id
      register: node_id_create_job
      shell: |
        import sys, ipaddress, math
        node_net       = ipaddress.IPv6Network('{{ authorities['node.domain']['network'] }}')
        node_net_bytes = int(node_net.network_address).to_bytes(16, 'big')
        node_net_pfxid = node_net_bytes[:math.ceil(node_net.prefixlen / 8)][1:]
        sys.stdout.write(node_net_pfxid.hex())
        sys.exit(0)
      args:
        executable: "{{ ansible_python.executable }}"

    - name: register node id
      set_fact:
        authorities: >-
          {{
              authorities|
              combine({
                'node.domain': authorities['node.domain']|
                combine({ 'id': node_id_create_job.stdout })
              })
          }}

- name: commit node id
  when: node_id_create_job.changed
  include_tasks: tasks/node-commit-authority-attr.yml
  vars:
    authority_name: node.domain
    authority_attr: id
