# Inputs:
# node_systemdb_path
#
# Outputs:
# domains
---
- name: load domains
  register: domains_load_job
  changed_when: false
  vars:
    inputs:
      db_path: "{{ node_systemdb_path }}"
  shell: |
    import sys, json, sqlite3
    inputs  = json.loads(sys.stdin.read())
    db_path = inputs['db_path']

    dbc     = sqlite3.connect(db_path).execute(
      'select attribute, value from {{ item }}_domain'
    )

    records = dbc.fetchall()
    domain  = {}

    for attr, val in records:
      domain[attr] = val

    sys.stdout.write(json.dumps(domain))
    sys.exit(0)
  args:
    executable: "{{ ansible_python.executable }}"
    stdin: "{{ inputs|to_json }}"
  loop:
    - system
    - node

- name: register domains
  vars:
    scope: "{{ item.item }}"
    attrs: "{{ item.stdout|from_json }}"
  set_fact:
    domains: "{{ domains|default({})|combine({ scope: attrs }) }}"
  loop: "{{ domains_load_job.results }}"
  loop_control:
    label: "{{ scope }}"
