# Inputs:
# hostvars.localhost.project_resources_dir
#
# Outputs:
# project_resources
---
- name: load resources
  set_fact:
    project_resources:
      services : "{{ lookup('file', hostvars.localhost.project_resources_dir ~ '/services.yml') | from_yaml }}"
      volumes  : "{{ lookup('file', hostvars.localhost.project_resources_dir ~ '/volumes.yml')  | from_yaml }}"
      routes   : "{{ lookup('file', hostvars.localhost.project_resources_dir ~ '/routes.yml')   | from_yaml }}"
