# Inputs:
# project_name
# project_resources
---
- name: project volume storage
  file:
    path: "{{ node_volstorage_mountpoint }}/{{ project_name }}"
    state: directory

- name: volume mountpoints
  file:
    path: "{{ vol_mountpoint }}"
    state: directory
  loop: "{{ project_resources['volumes'] }}"
  loop_control:
    loop_var: vol
    label: "{{ vol.name }}"
  vars:
    vol_mountpoint: "{{ node_volmount_path }}/{{ project_name }}/{{ vol.name }}"

- name: create volumes
  register: vols_create_job
  command: truncate -s {{ vol.size }} {{ vol_path }}
  args:
    creates: "{{ vol_path }}"
  loop: "{{ project_resources['volumes'] }}"
  loop_control:
    loop_var: vol
    label: "{{ vol.name }}"
  vars:
    vol_path: "{{ node_volstorage_mountpoint }}/{{ project_name }}/{{ vol.name }}"

- name: format volumes
  filesystem:
    dev: "{{ vol_path }}"
    fstype: xfs
  loop: "{{ project_resources['volumes'] }}"
  loop_control:
    loop_var: vol
    label: "{{ vol.name }}"
  vars:
    vol_path: "{{ node_volstorage_mountpoint }}/{{ project_name }}/{{ vol.name }}"

- name: mount volumes
  loop: "{{ project_resources['volumes'] }}"
  mount:
    src: "{{ vol_path }}"
    path: "{{ vol_mountpoint }}"
    state: mounted
    fstype: xfs
    opts: loop,nofail
  loop_control:
    loop_var: vol
    label: "{{ vol.name }}"
  vars:
    vol_path: "{{ node_volstorage_mountpoint }}/{{ project_name }}/{{ vol.name }}"
    vol_mountpoint: "{{ node_volmount_path }}/{{ project_name }}/{{ vol.name }}"

- name: initial data imports
  when: vol_create_job.changed
  include_tasks: tasks/project-volume-import-{{ vol_import_taskname }}.yml
  loop: "{{ lookup('subelements', vols_create_job.results, 'vol.import.srcs', wantlist=True) }}"
  loop_control:
    label: "{{ vol.name }}"
  vars:
    vol_create_job      : "{{ item[0] }}"
    vol                 : "{{ vol_create_job.vol }}"
    vol_name            : "{{ vol.name }}"
    vol_import_src      : "{{ item[1] }}"
    vol_import_taskname : "{% if vol_import_src.name in ('http', 'https') %}remote{% else %}fromimg{% endif %}"
