# Inputs:
# project_repo_url
# project_ref
#
# Inputs:
# project_compose_path
#
# Outputs:
# project_compose_cfg
# project_resources
---
- name: load compose file
  set_fact:
    project_compose_cfg: "{{ lookup('file', project_compose_path)|from_yaml }}"

- name: parse compose file
  import_tasks: tasks/python-parse-project-resources.yml
