# Inputs:
# project_repo_url
# project_ref
#
# Outputs:
# project_compose_cfg
# project_resources
---
- name: project paths
  import_tasks: tasks/project-local-paths.yml

- name: project home
  file:
    path: "{{ project_repo_dir|dirname }}"
    state: directory

- name: clone project
  when: project_repo_url|length > 0
  git:
    repo: "{{ project_repo_url }}"
    dest: "{{ project_repo_dir }}"
    version: "{{ project_ref }}"
    depth: 1
    recursive: false

- name: load compose file
  set_fact:
    project_compose_cfg: "{{ lookup('file', project_compose_path)|from_yaml }}"

- name: parse compose file
  import_tasks: tasks/python-parse-project-resources.yml
