---
- name: path variables
  import_tasks: tasks/project-records-vars.yml

- name: create dump dir
  file:
    path: "{{ project_records_dir }}"
    state: directory

- name: dump records
  vars:
    dump_path: "{{ project_records_dir }}/{{ item }}.yml"
  copy:
    dest: "{{ dump_path }}"
    content: |
      {{ project_resources[item]|to_nice_yaml(indent=2) }}
  loop:
    - services
    - volumes
    - routes
