# Inputs:
# project_resources_dir
---
- name: create dump dir
  file:
    path: "{{ project_resources_dir }}"
    state: directory

- name: dump resource records
  vars:
    dump_path: "{{ project_resources_dir }}/{{ item }}.yml"
  copy:
    dest: "{{ dump_path }}"
    content: |
      {{ project_resources[item]|to_nice_yaml(indent=2) }}
  loop:
    - services
    - volumes
    - routes
