# Inputs:
# node_systemdb_path
---
- name: load node network prefix
  register: nodenet_load_job
  changed_when: false
  vars:
    inputs:
      db_path: "{{ node_systemdb_path }}"
  shell: |
    import sys, json, sqlite3
    inputs  = json.loads(sys.stdin.read())
    db_path = inputs['db_path']

    dbc     = sqlite3.connect(db_path).execute(
      'select value from node_domain where attribute = "network"'
    )

    network = dbc.fetchone()[0]

    sys.stdout.write(network)
    sys.exit(0)
  args:
    executable: "{{ ansible_python.executable }}"
    stdin: "{{ inputs|to_json }}"

- name: register node network prefix
  set_fact:
    node_network: "{{ nodenet_load_job.stdout }}"
