# Inputs:
# new_subnet_supernet
# new_subnet_pfxlen
#
# Outputs:
# new_subnet
---
- name: generate new subnet
  register: subnet_gen_job
  shell: |
    {{ lookup('file', playbook_dir ~ '/python/scripts/gen-subnet.py') }}
  vars:
    inputs:
      supernet: "{{ new_subnet_supernet }}"
      subnet_pfxlen: "{{ new_subnet_pfxlen }}"
  args:
    stdin: "{{ inputs|to_json }}"
    executable: "{{ ansible_playbook_python }}"
  changed_when: false
  delegate_to: localhost
  become: false

- name: register generated subnet
  set_fact:
    new_subnet: "{{ subnet_gen_job.stdout }}"
