# Inputs:
# new_supernet_pfxlen
#
# Outputs:
# new_supernet
---
- name: generate new supernet
  register: supernet_gen_job
  shell: |
    {{ lookup('file', playbook_dir ~ '/python/scripts/gen-supernet.py') }}
  vars:
    inputs:
      pfxlen: "{{ new_supernet_pfxlen }}"
  args:
    stdin: "{{ inputs|to_json }}"
    executable: "{{ ansible_python.executable }}"
  changed_when: false

- name: register generated supernet
  set_fact:
    new_supernet: "{{ supernet_gen_job.stdout }}"
