# Inputs:
# new_subnet_supernet
# new_subnet_pfxlen
#
# Outputs:
# new_subnet
---
- name: generate new subnet
  register: subnet_gen_job
  command: "{{ ansible_python.executable }} {{ playbook_dir }}/python/scripts/gen-subnet.py"
  vars:
    inputs:
      supernet: "{{ new_subnet_supernet }}"
      subnet_pfxlen: "{{ new_subnet_pfxlen }}"
  args:
    stdin: "{{ inputs|to_json }}"
  changed_when: false

- name: register generated subnet
  set_fact:
    new_subnet: "{{ subnet_gen_job.stdout }}"
