apiVersion: v1
kind: Service
metadata:
  name: graylog-gelf
  namespace: kube-system
spec:
  type: ExternalName
  externalName: 192.168.223.12
  ports:
    - name: gelf-udp
      protocol: UDP
      port: 12201
    - name: gelf-tcp
      protocol: TCP
      port: 12201
