apiVersion: v1
kind: Service
metadata:
  name: graylog-gelf
  namespace: kube-system
spec:
  ports:
    - name: udp-gelf
      protocol: UDP
      port: 12201
    - name: tcp-gelf
      protocol: TCP
      port: 12201
