#!/usr/bin/env ansible-playbook
---
- name: Build project instances group
  hosts: localhost
  tasks:

    - name: project paths
      import_tasks: tasks/project-local-paths.yml

    - name: load service resource records
      register: load_svcs_job
      vars:
        records_load_dir: "{{ projects_home }}/{{ item }}/resources"
      set_fact:
        project_services: >-
          {{
            project_services|default({})|
            combine({
              item: lookup('file', records_load_dir ~ '/services.yml')|from_yaml
            })
          }}
      loop: "{{ groups['projects'] }}"

    - name: load volume resource records
      register: load_vols_job
      vars:
        records_load_dir: "{{ projects_home }}/{{ item }}/resources"
      set_fact:
        project_volumes: >-
          {{
            project_volumes|default({})|
            combine({
              item: lookup('file', records_load_dir ~ '/volumes.yml')|from_yaml
            })
          }}
      loop: "{{ groups['projects'] }}"

    - name: load route resource records
      register: load_routes_job
      vars:
        records_load_dir: "{{ projects_home }}/{{ item }}/resources"
      set_fact:
        project_routes: >-
          {{
            project_routes|default({})|
            combine({
              item: lookup('file', records_load_dir ~ '/routes.yml')|from_yaml
            })
          }}
      loop: "{{ groups['projects'] }}"

    - name: get project placement lists
      when: hostvars[item]['project_placement'] is defined
      set_fact:
        project_placements: >-
          {{
              (project_placements|default([])) + [
                { 'project': item, 'placement': hostvars[item]['project_placement'] }
              ]
          }}
      loop: "{{ groups['projects'] }}"

    - name: generate project instances inventory group
      vars:
        project_name: "{{ item[0].project }}"
        placement_host: "{{ item[1].host }}"
        svc_counts: "{{ item[1].svc_counts }}"
        project_instance: "{{ project_name }}.{{ placement_host }}"
      add_host:
        name: "{{ project_instance }}"
        groups:
          - project_instances
        ansible_host: "{{ hostvars[placement_host]['ansible_host']|default(placement_host) }}"
        project_services: "{{ project_services[project_name] }}"
        project_volumes: "{{ project_volumes[project_name] }}"
        project_routes: "{{ project_routes[project_name] }}"
        project_svc_counts: "{{ svc_counts }}"

      loop: "{{ lookup('subelements', project_placements, 'placement', wantlist=True) }}"
      loop_control:
        label: "{{ project_instance }}"
      changed_when: false
