#!/usr/bin/env ansible-playbook
---
- name: Build project instances group
  hosts: localhost
  tasks:

    - name: generate project instances inventory group
      vars:
        project_name: "{{ item[0].inventory_hostname }}"
        placement_node: "{{ item[1].node }}"
        instance_name: "{{ project_name }}.{{ placement_node }}"
      add_host:
        name: "{{ instance_name }}"
        groups:
          - project_instances
        ansible_host: "{{ hostvars[placement_node]['ansible_host']|default(placement_node) }}"
        ansible_user: "{{ node_admin_user }}"
        project_name: "{{ project_name }}"
        project_instance_svc_counts: "{{ item[1].svc_counts }}"
        project_instance_placement: "{{ item[1].node }}"

      loop: "{{ groups['projects']|map('extract', hostvars)|list|subelements('project_placement') }}"
      loop_control:
        label: "{{ instance_name }}"
      changed_when: false
