#!/usr/bin/env ansible-playbook
---
- name: Initialize and populate system database
  hosts: nodes
  become: true
  tasks:

    - name: initialize the system db
      vars:
        inputs:
          db_path: "{{ node_systemdb_path }}"
      shell: |
        import sys, json, sqlite3
        inputs  = json.loads(sys.stdin.read())
        db_path = inputs['db_path']
        db      = sqlite3.connect(db_path)
        db.executescript('''

          create table system_domain(
              attribute,
              value
          );
          create table node_domain(
              attribute,
              value
          );
          create table projects(
              name,
              attribute,
              value
          )

        ''')
        db.commit()
        db.close()
        sys.exit(0)
      args:
        executable: "{{ ansible_python.executable }}"
        stdin: "{{ inputs|to_json }}"
        creates: "{{ node_systemdb_path }}"

    - name: load domains
      import_tasks: tasks/node-load-domains.yml

    - name: populate domains
      include_tasks: "{{ domain_init_taskpath }}"
      loop: "{{ lookup('fileglob', playbook_dir ~ '/tasks/domains-init/*.yml', wantlist=True) }}"
      loop_control:
        loop_var: domain_init_taskpath
