#!/usr/bin/env ansible-playbook
---
- name: Intake project from docker-compose.yml
  hosts: localhost
  vars:
    project_repo_url     : "{{ lookup('env', 'PROJECT_GIT_URL') }}" # REQUIRED
    project_ref          : "{{ lookup('env', 'PROJECT_GIT_REF') }}" # REQUIRED
    project_name         : "{{ lookup('env', 'PROJECT_NAME') }}"
    project_compose_file : "{{ lookup('env', 'COMPOSE_FILE') }}"
    project_compose_path : "{{ (project_repo_dir ~ '/' ~ project_compose_file) | realpath }}"
  tasks:
    - name: validate input vars
      assert:
        that:
          - project_repo_url |length > 0
          - project_ref      |length > 0
        success_msg: required variables ok
        fail_msg:
          - 'missing one or more required variables'
          - 'project_repo_url = {{ project_repo_url }}'
          - 'project_ref      = {{ project_ref }}'

    - name: set default compose file
      when: project_compose_file|length == 0
      set_fact:
        project_compose_file: docker-compose.yml

    - name: set default project name
      when: project_name|length == 0
      set_fact:
        project_name: >-
          {% if project_repo_url|basename == '.git' -%}
          {{ project_repo_url|dirname|basename }}
          {%- else -%}
          {{ project_repo_url|basename|regex_replace('(.*)\.git', '\1') }}
          {%- endif %}

    - name: parse resources
      import_tasks: tasks/project-parse-resources.yml

    - name: dump project resources
      import_tasks: tasks/project-dump-resources.yml
