#!/usr/bin/env ansible-playbook
---
- name: Intake project from docker-compose.yml
  hosts: localhost
  vars:
    project_compose_path: "{{ lookup('env', 'COMPOSE_FILE') }}"
  tasks:
    - name: set default compose file
      when: project_compose_path|length == 0
      set_fact:
        project_compose_path: docker-compose.yml

    - name: load compose file
      set_fact:
        project_compose_cfg: "{{ lookup('file', project_compose_path)|from_yaml }}"

    - name: validate compose file
      register: compose_validate_job
      changed_when: false
      shell: |
        import sys
        sys.stdout.write(sys.stdin.read())
        sys.exit(0)
      args:
        executable: "{{ ansible_python.executable }}"
        stdin: "{{ project_compose_cfg|to_json }}"

    - name: parse project resources
      register: resource_parse_job
      changed_when: false
      command: "{{ ansible_python.executable }} {{ playbook_dir }}/python/scripts/parse-project-{{ item }}.py"
      args:
        stdin: "{{ project_compose_cfg|to_json }}"
      environment:
        PYTHONPATH: "{{ playbook_dir }}/python/lib"
      loop:
        - volumes
        - services
        - routes

    - name: show project resource records
      debug:
        msg: "{{ item.stdout|from_json }}"
      loop: "{{ resource_parse_job.results }}"
      loop_control:
        label: "{{ item.item }}"
