#!/usr/bin/env ansible-playbook
---
# Forcing the controller to run this play
# allows us to use the path hostvars.localhost.project_home
# later on to lookup project resources on the controller
- name: Load project home paths
  hosts:
    - nodes
    - localhost
  vars:
    project_name: system
  tasks:
    - name: project path
      import_tasks: tasks/project-local-paths.yml


- name: Deploy system project
  hosts: nodes
  vars:
    project_name: system
  tasks:

    - name: authorities
      import_tasks: tasks/node-load-authorities.yml

    - name: load system project resources
      import_tasks: tasks/project-load-resources.yml

    - name: push system project resource files
      include_tasks: tasks/project-dump-resources.yml

    - name: create system.domain network
      docker_network:
        name: system.domain
        enable_ipv6: true
        ipam_config:
          - subnet: "{{ authorities['system.domain']['network'] }}"

    - name: system project images
      import_tasks: tasks/project-images.yml

    - name: service authority records
      import_tasks: tasks/project-service-authorities.yml
      become: true

    - name: create volumes
      import_tasks: tasks/project-create-volumes.yml
      become: true

    - name: run services
      import_tasks: tasks/project-reconcile-services.yml
