#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars:
    node_systemdb_path: /tmp/system.db
  tasks:

    - import_tasks: tasks/node-load-authorities.yml
    - debug:
        var: authorities
