version: '2'

services:

  http-router:
    build: ../../images/haproxy-http-router
    volumes:
      - router-config:/usr/local/etc/haproxy
    networks:
      system:
    ports:
      - '${HTTP_PORT}:80'
    labels:
      civic-cloud.system.port.0.node : '80'
      civic-cloud.system.port.0.svc  : '80'

  static-http:
    image: nginx:1.19
    volumes:
      - static-data:/usr/share/nginx/html
    networks:
      system:
        aliases:
          - static-http.system.domain

volumes:
  router-config:
    labels:
      civic-cloud.size: 2G
      civic-cloud.import.src: http-router:/usr/local/etc/haproxy
  static-data:

networks:
  system:
