apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: openresty-edge
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        id: openresty-edge
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: openresty-edge
          image: openresty-edge:1.11.2.3r1
          ports:
            - containerPort: 80
              hostPort: 80
            - containerPort: 443
              hostPort: 443
        - name: resolver
          image: andyshinn/dnsmasq:2.76
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
