apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-shared-userdata
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16M
  volumeName: postgres-shared.userdata
