apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-shared-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16G
  volumeName: postgres-shared.data
